### ISSUE TITLE
There is no sword

### ISSUE THREAD

**Issue by dlgiovani** [AndreiBalan-dev/there-is-no-website#23]
![image](https://github.com/user-attachments/assets/231ccd7f-9a55-4f30-9b59-59fdd998317d)
I don't know if this page was supposed to show something other than the counter, not even my mouse appears.

**Comment by dlgiovani** [comment]
PS: it kinda works when I move my mouse, the counter goes up, but it is not consistent (even less consistent since I can't see the mouse)

**Comment by AndreiBalan-dev** [comment]
Hey! This was during a server outage from us :(
Could you please check again and let me know if you still have the same issue?

If the answer to my question above is yes, please let me know what browser you're using!

**Comment by dlgiovani** [comment]
yup, way better now. Things are loading and the voice is working too, I didn't realize it was missing too yesterday.
