### ISSUE TITLE
There is no video to break

### ISSUE THREAD

**Issue by dlgiovani** [AndreiBalan-dev/there-is-no-website#24]
![image](https://github.com/user-attachments/assets/3142e305-b832-4421-ab42-3c6337772668)
Most of the times the "video" components just disappear before I can "break" them more, making progress impossible.

**Comment by dlgiovani** [comment]
trace:

Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at i.bodies (https://www.thereisnoweb.site/assets/index-DVN-4uBO.js:66:69907)
    at i.world (https://www.thereisnoweb.site/assets/index-DVN-4uBO.js:66:66047)
    at P (https://www.thereisnoweb.site/assets/index-DVN-4uBO.js:66:62812)

**Comment by AndreiBalan-dev** [comment]
Same question as [**here**](https://github.com/AndreiBalan-dev/there-is-no-website/issues/23#issuecomment-2295123788).

**Comment by dlgiovani** [comment]
Solved as marked in the other question above.
